extends Node

# Dictionaries to hold name prefixes and suffixes for each race
var name_prefixes = {
	"HUMAN": ["Al","Da","El","Jo","Mar","Re","Ro","Sa","Thar","Wil","An","Bal","Cal","Dan","Ed","Fer","Gar","Hal","Ig","Jen","Kai","Lan","Mel","Nor","Or","Per","Quin","Rai","Sam","Tor","Uri","Val","Wes","Xan","Yor","Zan","Bry","Cor","Dre","Eli","Fel","Gil","Han","Ivor","Jon","Ker","Leo","Mor","Nel","Oth","Pax","Qui","Rod","Sim","Ter","Ulf","Van","Wyn","Xav","Yen","Zor"],
	"ELF": ["Ara","Eli","Lia","Tha","Syl","Fae","Gal","Ith","Mer","Ere","Ama","Bel","Cala","Dae","Ela","Fin","Glyn","Hela","Isil","Jae","Kae","Lora","Mira","Nai","Ola","Phae","Quen","Rae","Sari","Tani","Uri","Vala","Wyn","Xyra","Ylsa","Zara","Alen","Bryn","Cele","Dara","Elda","Fira","Gara","Hala","Ilya","Jora","Kira","Lyna","Mela","Nera","Oryn","Pela","Quil","Rina","Syla","Tara","Ulya","Vina","Wila","Xina","Yara","Zina","Elan","Leth","Ther","Ald","Fer","Gyl","Myla","Nym"],
	"DWARF": ["Bal","Dur","Gor","Thra","Dain","Khar","Bor","Thor","Dwal","Fur","Kaz","Bro","Grim","Nor","Rag","Ul","Bren","Bram","Drak","Erak","Fald","Gar","Har","Ivor","Kron","Lok","Mor","Nor","Orin","Rag","Thal","Var","Wulf","Zal","Arin","Bof","Darr","Fror","Gunn","Hel","Isil","Jor","Karn","Lan","Mal","Nir","Orr","Rin","Stor","Thram","Ulf","Varn","Zar","Ald","Brin","Dur","Fur","Gor","Har","Kil","Log","Mun","Nar","Orm","Rol","Sten","Thur","Ur","Varn","Wor","Zul"],
	"HALFLING": ["Bil","Fro","Sam","Mer","Pip","Lob","Ham","Ros","Bel","Jil","Gar","Wil","Tol","Lor","Hob","Bri","Mat","Nel","Per","Her","Fil","Gil","Nor","Jas","Lan","Mik","Nor","Oli","Poe","Qui","Reg","Sim","Tom","Vir","Wes","Xan","Yor","Zel","Ad","Ben","Cal","Dan","El","Fyn","Gwen","Hal","Ina","Jon","Kel","Lia","Mar","Ned","Ora","Pip","Que","Ryn","Sol","Tess","Ul","Vyn","Wyn","Xyl","Yva","Zan","Al","Bryn","Cel","Dom","Ell","Fel","Glen","Hugh","Is","Jed","Kip"],
	"GNOME": ["Bil","Gim","To","Fel","Nim","Zum","Clo","Jip","Quin","Fen","Xan","Wen","Vim","Zin","Tib","Kel","Jem","Pan","Lim","Bor","Yim","Gel","Mun","Ris","Tur","Wal","Ral","Pip","Min","Nim","Yen","Zen","Tym","Gan","Dur","Fiz","Hor","Bum","Wil","Jor","Pip","Lin","Lor","Mat","Nor","Per","Tes","Quen","Sin","Val","Win","Xel","Yel","Zan","Ban","Cin","Dol","Eld","Fon","Gil","Har","Iro","Jor","Kas","Lin","Mil","Nin","Oro","Pom","Qui","Sal","Tan","Vel","Wor","Xen","Yor","Zel"],
	"ORC": ["Gor","Grim","Ur","Thok","Rag","Mok","Krog","Lok","Vorg","Hak","Tor","Drak","Zug","Bur","Khan","Brak","Nok","Rak","Gul","Thar","Dar","Kor","Lag","Bor","Zog","Grok","Kraz","Mug","Nur","Bog","Gra","Kaz","Tor","Urg","Vor","Bar","Duk","Muk","Zar","Nar","Gar","Gath","Maz","Nor","Thrall","Urag","Zul","Drog","Rok","Skar","Vok","Wor","Xar","Yor","Zar","Thog","Krug","Brak","Dor","Zan","Grak","Nar","Kruk","Lug","Maz","Ork","Trak","Ugr","Vrak","Bog","Gul","Kor","Mar","Thal","Zog"],
	"TIEFLING": ["Aza","Bel","Cae","Des","Eli","Fae","Gor","Har","Ish","Jez","Kael","Lor","Mal","Nar","Ori","Pyr","Quar","Rav","Sor","Taz","Uri","Vas","Xar","Yaz","Zar","Azaz","Belar","Car","Damar","Ezor","Faen","Graz","Haz","Ivar","Jor","Khor","Lar","Morz","Naz","Orin","Par","Quen","Raz","Sar","Taz","Ulrik","Val","Xan","Yor","Zor"],
	"DRAGONBORN": ["Ald","Bal","Dar","Eld","Gar","Har","Ird","Jor","Kar","Laz","Mar","Nar","Orn","Par","Qor","Ral","Sar","Tar","Urd","Val","Waz","Xar","Yar","Zar","Arj","Bah","Dael","Eld","Fah","Gal","Hal","Ird","Jar","Kla","Lor","Mar","Ner","Ors","Paar","Qor","Ral","Sar","Tor","Urn","Vah","War","Xar","Yar","Zor"],
	"DROW": ["Ara","Bel","Dru","Eli","Fae","Gau","Hau","Ila","Jal","Kae","Lar","Mal","Nar","Ori","Phae","Quar","Ral","Sar","Tal","Uri","Vel","Wil","Xar","Yas","Zar","Bael","Cal","Dal","Elv","Faer","Gol","Hul","Ilm","Jez","Kil","Lys","Mar","Nol","Omr","Phyr","Quin","Ral","Sal","Taz","Ulvi","Vaz","Wyl","Xul","Yel","Zol"],
	"HALF ELF": ["Al","Bri","Cal","Del","El","Fa","Gal","Hal","Il","Jer","Kai","Lan","Mel","Nor","Ori","Per","Qua","Ral","Sam","Tar","Ul","Val","Wil","Xan","Yor","Zan","And","Ben","Car","Dav","Eth","Fin","Gar","Hen","Is","Jon","Ker","Leo","Mar","Nor","Or","Pau","Qua","Reb","Sam","The","Uri","Vic","Wal","Xan","Yan","Zac"],
	"HALF ORC": ["Gar","Grim","Ur","Thok","Rag","Mok","Krog","Lok","Vorg","Hak","Tor","Drak","Zug","Bur","Khan","Brak","Nok","Rak","Gul","Thar","Dar","Kor","Lag","Bor","Zog","Grok","Kraz","Mug","Nur","Bog","Gra","Kaz","Tor","Urg","Vor","Bar","Duk","Muk","Zar","Nar","Gar","Gath","Maz","Nor","Thrall","Urag","Zul","Drog","Rok","Skar","Vok","Wor","Xar","Yor","Zar","Thog","Krug","Brak","Dor","Zan","Grak","Nar","Kruk","Lug","Maz","Ork","Trak","Ugr","Vrak","Bog","Gul","Kor","Mar","Thal","Zog"],
	"AASIMAR": ["Aur","Cel","Dae","Eli","Faer","Gal","Hal","Ith","Jas","Kael","Lun","Mel","Nor","Ori","Phae","Quin","Rae","Sar","Tha","Uri","Val","Wyn","Xan","Yor","Zar","Ar","Bael","Cael","Dael","Ely","Fay","Gav","Han","Ilm","Jen","Kyr","Lor","Mer","Nir","Ol","Per","Qil","Rel","Sil","Ther","Ul","Ven","Wes","Xar","Yel","Zil"],
	"KENKU": ["Ak","Caw","Tik","Kra","Ick","Qik","Ruk","Twi","Zap","Eek","Chi","Tak","Pek","Qek","Zit","Ark","Bik","Dik","Fik","Gik","Hik","Ik","Jik","Kik","Lik","Nik","Oik","Pak","Rak","Sik","Tik","Uik","Vik","Wik","Xik","Yak","Zik","Ek","Ok","Ak","Ik","Uk","Ak","Ek","Ik","Ok","Uk","Eek","Ka","Kee","Koo","Ku","Kwe","Kwi","Kwik","Kwok","Kwa","Kwot","Klik","Klak","Klek","Klok","Klok","Kwak","Kwek"],
	"TABAXI": ["Jag","Lei","Keh","Pan","She","Tor","Zan","Sim","Kal","Rai","Mar","Tai","Zin","Haw","Chi","Rak","Tor","Vas","Nal","Tik","Fai","Kor","Nar","Zar","Man","Tar","Var","Sun","Fer","Nir","Ar","Dal","Tor","Rai","Tan","Kir","Fel","Sor","Lor","Sar","Fin","Kar","Mik","Ran","Sol","Tel","Tai","Zan","Jin","Tar","Kir","Dar","Sim","Tur","Var","Kor","Nar","Par","Zor","Al","Tor","Ran","Fer","Nir","Tan"],
	"LIZARDFOLK": ["Ss","Zal","Gor","Trak","Kek","Vos","Gar","Sha","Tor","Ras","Kal","Mar","Nor","Sar","Zek","Lok","Bar","Xar","Var","Dar","Tal","Lar","Or","Xor","Jas","Tas","Zor","Vel","Rak","Nek","Hor","Lar","Mol","Sar","Tek","Vor","Kur","Dar","Nor","Zas","Jor","Lor","Tor","Var","Vor","Sar","Nor","Mar","Dar","Tor","Kal","Lar","Kor","Far","Nar","Var","Zal","Kor","Tar","Sar","Nor","Kal","Dar","Vor","Zar"],
	"MERFOLK": ["Aqua","Neri","Coral","Del","Mari","Ocea","Pearl","Ser","Atlant","Ari","Marin","Lore","Nai","Kai","Pyr","Tide","Eli","Sei","Dru","Hydro","Nym","Mira","Cora","Ceru","Brine","Orca","Cel","Foam","Glyn","Har","Isla","Jen","Kel","Levi","Mir","Nar","Oce","Pel","Que","Rai","San","Tha","Uri","Val","Win","Xan","Yor","Zan","Ael","Bel","Cal","Dan","Ely","Fay","Gar","Hal","Ilm","Jon","Kel","Lin","Mel","Nor","Oro","Por","Quin","Ral","Sel","Tal","Ura","Val","Wyn","Xar","Yel","Zil"],
	"UNDEAD": ["Necro","Mor","Vlad","Than","Crypt","Grim","Drak","Mort","Raven","Skul","Vile","Dread","Dark","Gor","Shade","Grave","Zar","Nox","Umbr","Tomb","Bleak","Dire","Hav","Soul","Wraith","Ghoul","Phan","Lich","Coff","Rot","Gloom","Hel","Mal","Mour","Shade","Tor","Drak","Dusk","Abyss","Crow","Night","Pale","Reven","Sor","Veil","Bal","Thar","Kel","Kry","Zan","Xar","Ichor","Wight","Ereb","Obliv","Carc","Noct","Taint","Gloam","Sable","Void","Sepul","Shroud","Spect"],
	"TROLL": ["Grog","Brak","Dro","Urk","Rok","Skal","Grim","Thog","Zug","Krog","Gul","Mok","Tor","Rag","Hak","Gor","Dra","Nok","Kaz","Bog","Gruk","Krug","Murk","Ruk","Thr","Zar","Bra","Dor","Gar","Lok","Mar","Nor","Ork","Trak","Urn","Vor","Wor","Xar","Yar","Zor","Grog","Brak","Dor","Grim","Zug","Gul","Tor","Rag","Hak","Gor","Dra","Nok","Kaz","Bog","Krug","Ruk","Mok","Nar","Gor","Thr","Zar","Bra","Grok","Jor","Lor","Rak","Sar","Thor","Ver","Wil","Zar"],
	"FAIRY": ["Aura","Luna","Fae","Syl","Glim","Thistle","Dew","Star","Willow","Briar","Lila","Mar","Petal","Rose","Sun","Moon","Elora","Fira","Goss","Ivy","Jas","Kel","Lil","Mir","Nym","Orin","Pela","Quin","Rai","Sera","Tana","Uri","Vala","Wyn","Xyla","Yara","Zara","Blos","Cel","Dai","El","Flos","Gal","Hol","Ila","Jos","Kira","Lina","Mel","Ner","Olea","Pris","Rosa","Sel","Tia","Una","Via","Wila","Xina","Ylsa","Zina","Bria","Cal","Del","Eli","Fael","Gwen","Hala","Isil"],
	"DEMON": ["Az","Bel","Cai","Des","Eri","Fen","Gor","Har","Ish","Jez","Kra","Lil","Mal","Ner","Ozi","Paz","Qua","Raz","Sar","Taz","Urb","Val","Xar","Yaz","Zar","Asmod","Baal","Caim","Dagon","Ere","Fur","Gorgon","Hec","Ifrit","Jinn","Kraken","Luci","Meph","Nab","Orcus","Paim","Qli","Rav","Set","Tham","Utuk","Vesh","Xul","Yog","Zer","Amon","Bar","Caz","Dag","Ezr","Fell","Golg","Haz","Inu","Jor","Kaz","Laz","Mar","Nek","Omr","Pel","Quil","Rex","Sem","Tyr","Ul","Vel","Wyl","Xul","Yul","Zol"],
	"ANGEL": ["Ara","Cama","Domi","Eli","Gab","Han","Iri","Joph","Kara","Luci","Mika","Nath","Oph","Rapha","Sera","Uri","Zad","Ama","Bara","Chri","Dani","Etha","Gali","Haza","Isma","Jara","Kama","Luma","Metra","Nura","Opha","Pura","Rag","Sara","Tura","Vara","Wira","Xana","Yara","Zara","Amar","Bria","Celi","Daria","Eloi","Fara","Gari","Hara","Ilia","Jeni","Kali","Lara","Miri","Nara","Opal","Pala","Ravi","Seli","Tari","Uria","Vani","Wina","Xira","Yani","Zeli"],
	"GOBLIN": ["Gri","Snik","Zog","Grim","Brek","Snar","Kruk","Mog","Vark","Drog","Ruk","Krim","Fik","Jik","Pik","Krek","Grak","Draz","Zek","Muz","Glur","Nok","Snuk","Trik","Vrog","Brok","Trug","Grek","Zrag","Frek","Mik","Tik","Nark","Grib","Nix","Plak","Blik","Drok","Vek","Gruk","Rug","Nok","Sik","Juk","Trak","Zak","Blek","Freg","Snig","Tro","Dik","Kluk","Grak","Zrak","Mok","Drek","Grik","Brok","Trik","Krag","Zik"],
	"VAMPIRE": ["Drac","Vlad","Alu","Strah","Nos","Sang","Lil","Kain","Luci","Mor","Val","Ser","Rav","Zar","Dar","Lam","Thal","Vic","Mar","Sel","Len","Kar","Nef","Tal","Rav","Rhi","Ala","Mor","Eli","Gab","Dra","Lor","Orl","Rav","Lil","Az","Bel","Cai","Des","Eri","Fen","Gor","Har","Ish","Jez","Kra","Lil","Mal","Ner","Ozi","Paz","Qua","Raz","Sar","Taz","Urb","Val","Xar","Yaz","Zar","Asmod","Baal","Caim","Dagon","Ere","Fur","Gorgon","Hec","Ifrit","Jinn","Kraken","Luci","Meph","Nab"],
	"LYCAN": ["Fang","Wolf","Lup","Gar","Fenr","Ald","Thal","Ra","Grim","Lok","Rav","Bar","Lyk","Var","Rok","Nath","Thorn","Dur","Fen","Skal","Krag","Fur","Myr","Vor","Tyr","Kaz","Mor","Tor","Rak","Nar","Val","Bal","Zan","Lor","Or","Lyc","Gar","Jor","Kaz","Luk","Myr","Rog","Thal","Ur","Vor","Wulf","Xar","Yor","Zor","Lup","Ald","Fenr","Rav","Lok","Rok","Grim","Var","Nath","Thorn","Dur","Fen","Skal","Krag","Fur","Myr","Vor","Tyr","Kaz","Mor","Tor","Rak","Nar","Val","Bal"],
	"CYCLOPS": ["Brak","Gor","Zar","Krag","Thar","Ulf","Dra","Grim","Vok","Nor","Zog","Thok","Rak","Mor","Tor","Brol","Kron","Gol","Zug","Har","Nok","Dum","Var","Lor","Thur","Grol","Kaz","Ork","Trom","Gar","Urk","Lug","Bol","Mar","Dar","Nar","Vorn","Jor","Kal","Grok","Tor","Vor","Krag","Hor","Zan","Brok","Krom","Drog","Gor","Nor","Tar","Gral","Maz","Orn","Rok","Sar","Thal","Vor","Zor","Gran","Mur","Karn","Tor","Dar","Lor","Brol","Kaz","Thur","Gar","Nok","Krag","Trom","Grol","Var","Krag","Nor","Grim","Zor"],
	"GIANT": ["Brak","Gor","Thar","Ulf","Dra","Grim","Vok","Nor","Zog","Thok","Rak","Mor","Tor","Brol","Kron","Gol","Har","Nok","Dum","Var","Lor","Thur","Grol","Kaz","Ork","Trom","Gar","Urk","Lug","Bol","Mar","Dar","Nar","Vorn","Jor","Kal","Grok","Vor","Krag","Hor","Zan","Brok","Krom","Drog","Nor","Tar","Gral","Maz","Orn","Rok","Sar","Vor","Zor","Gran","Mur","Karn","Tor","Lor","Brol","Kaz","Thur","Gar","Nok","Trom","Grol","Var","Krag","Nor","Grim","Zor","Dron","Val","Fur","Kel","Gal","Zal","Vor","Wor","Xar","Yar","Zar"],
	"OGRE": ["Brak","Gor","Thok","Ulf","Dra","Grim","Vok","Nor","Zog","Rak","Mor","Tor","Brol","Kron","Gol","Har","Nok","Dum","Var","Lor","Thur","Grol","Kaz","Ork","Trom","Gar","Urk","Lug","Bol","Mar","Dar","Nar","Vorn","Jor","Kal","Grok","Vor","Krag","Hor","Zan","Brok","Krom","Drog","Nor","Tar","Gral","Maz","Orn","Rok","Sar","Vor","Zor","Gran","Mur","Karn","Tor","Lor","Brol","Kaz","Thur","Gar","Nok","Trom","Grol","Var","Krag","Nor","Grim","Zor","Dron","Val","Fur","Kel","Gal","Zal","Vor","Wor","Xar","Yar","Zar","Gor","Thok","Brug","Maz","Duk","Mug","Hak","Nar","Bok","Kuz","Urn","Trak","Fulg","Rug","Barg","Zag","Nok","Dar","Krug","Lok","Var","Durg","Bar","Thar","Zar"],
	"HARPY": ["Al","Brae","Clio","Dael","Enyo","Fury","Gla","Harp","Ixi","Juno","Kali","Lore","Mira","Nera","Orea","Phae","Quila","Rhea","Sela","Tari","Ursa","Vala","Wila","Xeni","Yara","Zara","Ala","Bel","Cyn","Des","Ela","Fael","Grae","Har","Isis","Jas","Kira","Lae","Maer","Nys","Ori","Pho","Qari","Ryn","Syra","Tara","Una","Vira","Wren","Xyla","Ylis","Zil","Aer","Bry","Cala","Del","Eri","Fey","Gal","Hael","Iris","Jyn","Kael","Lia","Mys","Nael","Oph","Pry","Quel","Sia","Thea","Ura","Vyn","Wyn","Xia","Yna","Zal"],
	"MINOTAUR": ["Aster","Brak","Crag","Demos","Ekon","Farr","Gor","Harr","Iro","Jax","Krag","Loth","Moro","Nox","Orus","Prax","Quar","Rok","Skor","Thar","Urgo","Varr","Wroth","Xar","Yar","Zor","Aster","Bov","Cyn","Drex","Erak","Fark","Grek","Hrak","Izar","Jorr","Krax","Lark","Morn","Nork","Orn","Pax","Qrax","Rorn","Skar","Tor","Urax","Vark","Wrak","Xarn","Yorn","Zarn","Brak","Gor","Krag","Thar","Nox","Skor","Loth","Prax","Urgo","Jax","Wroth","Orus","Harr","Varr","Demos","Crag","Moro","Farr","Rok","Quar"],
	"KOBOLD": ["Ax","Bik","Crik","Dax","Ek","Fix","Gak","Hix","Ix","Jik","Krax","Lix","Mox","Nix","Orix","Pix","Qik","Rax","Snik","Trix","Ux","Vik","Wix","Xik","Yik","Zik","Ak","Bok","Crix","Dak","Ek","Fok","Gik","Hok","Ik","Jak","Krik","Lik","Mak","Nik","Ok","Pak","Qrik","Rak","Sak","Tik","Uk","Vak","Wak","Xak","Yak","Zak","Ax","Bik","Crik","Dax","Ek","Fix","Gak","Hix","Ix","Jik","Krax","Lix","Mox","Nix","Orix","Pix","Qik","Rax","Snik","Trix"],
	"BEAST": ["Fang","Claw","Roar","Growl","Snarl","Hiss","Bite","Pounce","Strike","Slash","Talon","Venom","Prowl","Howl","Grim","Snap","Fierce","Savage","Wild","Brutal","Feroc","Rage","Fury","Tempest","Thunder","Storm","Blaze","Ash","Flame","Inferno","Razor","Scorch","Blitz","Dash","Flash","Streak","Blaze","Flare","Bolt","Jolt","Sear","Burn","Crush","Smash","Crash","Bash","Rampage","Wrath","Vex","Havoc","Chaos","Wrath","Dread","Dire","Scorn","Blight","Plague","Hex","Cursed","Doom","Shade","Shadow","Phantom","Specter","Wraith","Ghoul","Ghost","Spirit","Haunt","Poltergeist","Revenant","Banshee","Lurker","Watcher","Seeker"],
	"CHIMERA": ["Drak","Flam","Gor","Hyd","Chir","Myth","Thun","Ter","Vol","Ech","Mim","Gry","Wiv","Man","Lev","Phe","Pyr","Cer","Hyd","Chi","Zyg","Ech","Har","Min","Sag","Hyd","Pan","Cer","Chi","Bla","Sha","Wol","Dra","Tor","Lio","Bat","Ven","Tox","Lur","Gri","Ser","Med","Vul","Bla","Sha","Mag","Lyn","Gla","Sca","Ver","Nox","Mal","Twi","Dor","Rag","Lan","Bra","Zar","Fer","Mar","Xen","Hor","Dur","Myn","Tor","Wyr","Trin","Vex","Xar","Yar","Zar","Drak","Flam","Gor","Hyd","Chir","Myth","Thun","Ter","Vol","Ech","Mim","Gry","Wiv","Man","Lev","Phe","Pyr","Cer","Hyd","Chi","Zyg","Ech"],
	"DRAGON": ["Azor","Baler","Draco","Fafnir","Galad","Havoc","Ignis","Jormun","Kaldor","Lorcan","Magnus","Nyx","Obsid","Pyros","Quetzal","Ragnar","Saphir","Tiamat","Umbra","Vorath","Wrath","Xarath","Ysera","Zerath","Alduin","Bahamut","Cinder","Drogon","Ember","Frost","Grendel","Hydra","Inferna","Jade","Kryos","Lyran","Malach","Neroth","Onyx","Pyral","Quarath","Razael","Smaug","Talion","Umbrus","Valtor","Wyrm","Xenith","Ydra","Zalath","Andar","Braxis","Calyx","Drael","Eryndor","Fangor","Glaur","Hesper","Isen","Jalor","Kelthar","Lazur","Mordred","Nith","Ormir","Phaed","Qalith","Rhyzor","Sargor","Thalor","Ulthar","Vyrn","Wyrm","Xaroth","Ylthar","Zaroth"]
}

var name_suffixes = {
	"HUMAN": ["ton","den","las","rin","mond","ver","win","bert","ford","rick","dor","lyn","man","ward","tus","mar","nald","vik","gorn","dric","mir","lok","vald","tan","wyn","lan","rich","vil","dane","ros","gret","nard","ster","thor","mund","ran","gas","rak","vin","dan","wulf","hart","lin","mer","tin","dar","gorn","vyn","sten","vane","rid","san","vin","kan","ver","gar","tel","wyn","thur","rak","zel","ban","rad","sen","tar","brand","gorn","wil","helm","ner","ven","grid","lon","rit"],
	"ELF": ["riel","driel","thiel","wyn","lana","nara","lara","rion","las","dir","fen","lor","veth","mir","rin","sil","wen","thal","nor","ndil","lia","nas","rian","deth","lael","ndor","ria","fiel","rian","nwen","thel","dil","ndis","mir","riel","ra","ther","nis","lass","dan","dir","nath","lor","vin","til","sel","ris","ron","dil","vael","win","ran","nis","nith","wen","raen","vyn","lias","deth","len","ril","thas","lor","nith","mel","lis","daer","ren","rin","tiel","sira","lyl"],
	"DWARF": ["in","ik","ain","rak","dal","gar","nir","tor","grim","bold","dor","mund","fist","horn","krag","bald","rik","dren","hild","lok","mar","norn","or","rek","stan","thor","vin","var","zan","bard","drak","fell","gard","helm","kron","lorn","mir","nor","rek","skel","thur","vor","wald","zor","an","dur","gar","in","lin","mod","nar","or","rak","skar","tin","vor","wal","zor","ak","gar","lin","mund","nar","ran","sul","tor","vin","zor","fel","grim","harn","kar","lin","nath"],
	"HALFLING": ["bo","lo","do","lin","wise","foot","toe","bel","thorn","brook","worth","buckle","fallow","green","hill","moon","nook","pipe","shine","tallow","water","willow","wise","dale","foot","glen","hallow","leaf","mead","pip","reed","thorn","vale","weave","brook","dusk","fern","glow","hollow","light","moss","quill","shade","thorn","vale","wynn","yeard","zale","bale","fern","glen","hol","lock","moon","nill","quill","shade","tin","vell","wynn","zan","dan","finn","hall","leaf","moor","nell","quin","row","tan","vell","wick","yew","zan","fen","glow","hollow","lint","morn","pike"],
	"GNOME": ["by","rin","bum","tum","wyn","bim","kel","gel","min","bin","nip","nob","rick","dle","fiz","del","per","tom","wick","zell","dor","tiz","top","wig","lip","sip","pip","tim","wick","vin","zor","won","mip","pip","tin","nim","fizz","whistle","blip","snap","flop","drip","peb","lick","lup","bud","tuff","quill","snip","tag","wick","zap","zop","whiz","pop","twist","drop","blip","spark","tap","gim","kib","lob","nip","pip","zip","trap","pip","kit","lit","mar","tib","zam","dorp","zip","nim","blim","jin"],
	"ORC": ["gar","thak","mak","gash","ruk","tok","gor","lag","zuk","rok","kar","dush","mok","gor","nar","rog","drok","zul","tak","bur","guk","dok","mog","kur","dar","vok","lur","zar","goth","nok","tok","bar","dor","zak","krag","luk","nar","gash","vor","dak","rok","grok","zug","mur","ruk","dreg","mak","kar","zor","thok","gar","ruk","bar","zor","dag","mog","kar","dok","vok","mok","gur","zar","lok","mur","drok","gor","kar","goth","tok","vor","luk","zak","zar","ruk","tor","nar","grog","dak","mog"
,"'gar","'thak","'mak","'gash","'ruk","'tok","'gor","'lag","'zuk","'rok","'kar","'dush","'mok","'gor","'nar","'rog","'drok","'zul","'tak","'bur","'guk","'dok","'mog","'kur","'dar","'vok","'lur","'zar","'goth","'nok","'tok","'bar","'dor","'zak","'krag","'luk","'nar","'gash","'vor","'dak","'rok","'grok","'zug","'mur","'ruk","'dreg","'mak","'kar","'zor","'thok","'gar","'ruk","'bar","'zor","'dag","'mog","'kar","'dok","'vok","'mok","'gur","'zar","'lok","'mur","'drok","'gor","'kar","'goth","'tok","'vor","'luk","'zak","'zar","'ruk","'tor","'nar","'grog","'dak","'mog"],
	"TIEFLING": ["zar","riel","xar","zor","thos","riel","ros","mon","vash","nir","zor","dros","von","lam","rith","thal","nar","rax","ros","len","vis","ral","drath","var","nesh","zor","rith","zon","phos","ras","zan","kos","lir","thar","von","zal","kar","nel","vor","rix","nar","ral","zar","ril","xon","dor","vash","mir","dor","kas","nel","rath","thar","ron","vor","zil","nar","xen","rin","vos","gor","sal","nar","ral","van","zor","lor","mar","vin","zar","xor","lis","zal"],
	"DRAGONBORN": ["dras","gorn","nax","thar","vyr","zarn","kash","mor","dar","rax","tan","zor","kan","var","dar","thor","gol","nar","vor","tar","kar","vyr","dar","gor","nan","lar","zor","kar","vax","dral","mor","var","dar","kar","nor","zar","tan","vor","dan","kar","nar","gorn","var","dar","mor","kar","nar","zor","dar","tar","karn","vor","zan","dar","kar","nor","var","tan","kar","dar","nar","zor","dan","kar","nar","var","dar","gorn","zor","tan"],
	"DROW": ["ri","na","dra","sha","thra","vel","zel","nil","ra","sra","tria","xil","lyn","rae","sil","nor","sha","tyn","vra","nys","vyll","za","tra","ral","syl","zir","ra","dra","sil","nor","sha","thra","xil","lyn","ra","syl","vin","xil","dra","ril","sha","thra","vyn","ril","dra","sha","thra","vin","nor","lyn","syl","ral","za","tra","nel","dra","syl","vyn","sha","ril","lyn","vra","xil","dra","sha","tyn","ral","nel","vyn","syl","ral","za","tra"],
	"HALF ELF": ["don","len","ras","vin","mond","wen","ron","las","rin","son","vir","dar","thal","mir","len","tan","lis","wen","ria","dar","las","nin","ren","tir","ver","win","lin","mon","dar","nion","riel","mir","lis","van","wen","lin","vor","ran","lis","mir","den","lis","son","ver","ren","tan","mir","las","nel","rin","vin","nor","lin","mir","ven","don","ter","ris","dar","win","lor","nel","dan","ven","lon","mir","nor","lin","tan","lis","vin","vor","ron"],
	"HALF ORC": ["gar","thak","mak","gash","ruk","tok","gor","lag","zuk","rok","kar","dush","mok","gor","nar","rog","drok","zul","tak","bur","guk","dok","mog","kur","dar","vok","lur","zar","goth","nok","tok","bar","dor","zak","krag","luk","nar","gash","vor","dak","rok","grok","zug","mur","ruk","dreg","mak","kar","zor","thok","gar","ruk","bar","zor","dag","mog","kar","dok","vok","mok","gur","zar","lok","mur","drok","gor","kar","goth","tok","vor","luk","zak","zar","ruk","tor","nar","grog","dak","mog","'gar","'thak","'mak","'gash","'ruk","'tok","'gor","'lag","'zuk","'rok","'kar","'dush","'mok","'gor","'nar","'rog","'drok","'zul","'tak","'bur","'guk","'dok","'mog","'kur","'dar","'vok","'lur","'zar","'goth","'nok","'tok","'bar","'dor","'zak","'krag","'luk","'nar","'gash","'vor","'dak","'rok","'grok","'zug","'mur","'ruk","'dreg","'mak","'kar","'zor","'thok","'gar","'ruk","'bar","'zor","'dag","'mog","'kar","'dok","'vok","'mok","'gur","'zar","'lok","'mur","'drok","'gor","'kar","'goth","'tok","'vor","'luk","'zak","'zar","'ruk","'tor","'nar","'grog","'dak","'mog"],
	"AASIMAR": ["iel","on","iel","thiel","ron","dor","win","dar","riel","lin","thas","nor","wyn","vyn","ther","iel","nor","wyn","riel","nar","lyn","nar","siel","tar","vor","eth","las","mir","riel","ron","win","dar","vor","win","dil","nar","thas","lin","sil","nor","rith","nor","rin","var","tan","riel","dor","nor","riel","tar","win","nar","riel","dor","win","nar","dil","nor","tar","rith","wyn","nor","mir","win","dar","iel","nor","win","dar","nor","win","rith","lyn","tar","dar","nor"],
	"KENKU": ["awk","awk","eek","eek","ik","ik","awk","awk","awk","eek","ik","awk","eek","awk","awk","eek","ik","eek","awk","awk","ik","ik","awk","eek","awk","eek","ik","awk","ik","eek","ik","awk","ik","awk","eek","awk","ik","ik","ik","ik","eek","ik","eek","ik","ik","awk","awk","awk","ik","ik","eek","ik","ik","awk","eek","ik","ik","ik","ik","ik","ik","ik","ik","ik","ik","ik","ik","ik","ik","ik","ik","ik"],
	"TABAXI": ["kan","ran","nir","lan","sar","mar","tal","var","tar","dar","mir","zar","kir","tan","var","dar","lor","zar","lir","sar","tir","nar","mar","zar","nir","kar","sar","tar","var","dar","nir","zar","kar","nar","mar","var","dar","tar","lar","zar","mar","var","lar","zar","dar","kar","sar","tar","mar","lar","tar","zar","dar","kar","zar","tar","lar","kar","zar","dar","lar","sar","kar","tar","lar","zar","dar","lar","sar","tar","zar","kar","dar","tar","sar","mar","var","lar","tar","zar","dar","kar","sar","tar"],
	"LIZARDFOLK": ["ss","rak","kar","tar","zor","nar","thar","lar","sar","dar","kar","var","lor","sar","tar","zar","mar","tar","dar","zar","kar","nar","dar","kar","sar","lar","var","tar","zar","sar","lar","var","dar","tar","kar","nar","lar","var","dar","tar","sar","lar","kar","nar","dar","kar","sar","lar","var","tar","zar","mar","lar","var","tar","dar","kar","sar","tar","zar","nar","lar","sar","kar","tar","zar","mar","kar","sar","lar","tar","zar","nar","kar","sar","dar","var","tar","zar","lar","kar","sar","dar","tar"],
	"MERFOLK": ["Aqua","Neri","Coral","Del","Mari","Ocea","Pearl","Ser","Atlant","Ari","Marin","Lore","Nai","Kai","Pyr","Tide","Eli","Sei","Dru","Hydro","Nym","Mira","Cora","Ceru","Brine","Orca","Cel","Foam","Glyn","Har","Isla","Jen","Kel","Levi","Mir","Nar","Oce","Pel","Que","Rai","San","Tha","Uri","Val","Win","Xan","Yor","Zan","Ael","Bel","Cal","Dan","Ely","Fay","Gar","Hal","Ilm","Jon","Kel","Lin","Mel","Nor","Oro","Por","Quin","Ral","Sel","Tal","Ura","Val","Wyn","Xar","Yel","Zil"],
	"UNDEAD": ["thor","mour","lock","von","dred","nox","grim","shade","vile","gore","shade","grim","goth","tomb","mor","raith","thorn","tar","zar","mar","gore","skull","vile","gloom","grim","lock","shard","mourn","tide","tomb","dark","grave","gloom","soul","ghast","mor","lock","thorn","grim","vile","shade","zorn","mor","grim","shard","veil","soul","tar","grim","wraith","mour","tomb","gore","shade","mourn","tar","grim","zorn","wraith","veil","gloom","grim","lock","soul","ghast","mor","lock","tar","grim","shade","vile","gloom","grim","shard","veil","soul","tar","grim","wraith","mour","tomb"],
	"TROLL": ["nok","gar","ruk","tok","gorn","kar","thak","mok","zor","rak","dar","gor","lag","zuk","nar","vok","rok","zar","gash","mur","tak","lur","goth","tok","kur","dush","nok","kar","dok","bar","gor","zak","krag","lur","vok","dar","rok","gar","lur","gor","tok","kar","zar","gash","gorn","nar","gor","lag","zuk","rok","zar","thok","gash","mur","tak","lur","goth","tok","kur","dush","nok","kar","dok","bar","gor","zak","krag","lur","vok","dar","rok","gar","lur","gor","tok","kar","zar","gash","gorn","nar","gor","lag","zuk","rok","zar","thok","gash","mur","tak","lur","goth","tok","kur","dush","nok","kar","dok"],
	"FAIRY": ["bell","lily","shine","wing","blossom","spark","glow","petal","dew","gleam","flame","frost","leaf","song","star","whisper","moon","ray","mist","brook","fay","whistle","dusk","thorn","glade","breeze","flare","dust","bloom","flutter","glee","rain","spray","dream","shine","flutter","spark","petal","gleam","star","moon","ray","brook","fay","whisper","thorn","glade","dust","bloom","glee","rain","spray","shine","flare","breeze","glade","spark","whisper","dusk","thorn","flare","dust","glow","rain","dew","shine","star","petal","glade","frost","whisper","glow","spark","glee","ray","moon","mist","brook","glade","breeze","dust","bloom"],
	"DEMON": ["modius","zebub","fay","moth","iel","nix","gon","rith","mael","kal","toth","zar","phas","brim","ra","rith","voth","thoth","goth","khan","mor","vor","rex","ash","riel","gor","rax","rin","zil","rith","kan","zar","gorn","rax","thar","kor","gor","rax","rin","zil","thar","zor","vax","rim","vorn","zar","kel","gor","thas","mor","rax","goth","tar","rik","kel","gor","rax","gorn","mor","vax","rim","nar","zar","thas","goth","vor","rax","kel","gor","vorn","zar","kel","gor","thas","mor","vax","rim","vorn","zar","kel","gor","thas","mor","vax","rim","vorn","zar","kel","gor","thas","mor","vax","rim","vorn","zar","kel","gor","thas","mor"],
	"ANGEL": ["el","iel","ael","riel","rael","iel","mael","al","hael","iel","ael","riel","rael","iel","mael","al","hael","iel","ael","riel","rael","iel","mael","al","hael","iel","ael","riel","rael","iel","mael","al","hael","iel","ael","riel","rael","iel","mael","al","hael","iel","ael","riel","rael","iel","mael","al","hael","iel","ael","riel","rael","iel","mael","al","hael","iel","ael","riel","rael","iel","mael","al","hael","iel","ael","riel","rael","iel","mael","al","hael","iel","ael","riel","rael","iel","mael","al","hael","iel","ael","riel","rael","iel","mael","al","hael","iel","ael","riel","rael","iel","mael","al","hael"],
	"GOBLIN": ["git","snag","tik","zog","nuk","rik","grub","lok","zok","krag","murk","grot","tik","burk","nib","grak","rig","nok","zuk","vik","zik","nok","gurk","zik","grok","turk","zik","nak","rog","mok","ruk","tok","zuk","tik","grok","nik","grik","zog","rug","grot","nik","ruk","grak","mok","rag","zik","turk","zak","grok","nak","vik","krak","mok","nug","zik","nak","rok","zog","rik","gurk","nak","grok","vik","zak","gurk","krak","nak","grok","zuk","nak","mok","rag","gurk","mok","nik","rak","gurk","nak","rok","vik"],
	"VAMPIRE": ["ula","mir","von","strahd","feratu","uire","ith","kith","ard","cus","eria","ath","aine","eus","dreth","orin","elas","tina","inus","an","ith","emir","as","orus","ak","ira","ys","on","ius","an","or","azar","oth","ius","ath","oros","in","eon","on","as","ar","is","ar","thos","riel","ros","mon","vash","nir","zor","dros","von","lam","rith","thal","nar","rax","ros","len","vis","ral","drath","var","nesh","zor","rith","zon","phos","ras","zan","kos","lir","thar","von","zal","kar","nel","vor","rix","nar","ral","zar","ril","xon","dor","vash","mir","dor","kas","nel","rath","thar","ron","vor","zil","nar","xen","rin","vos","gor","sal","nar","ral","van","zor","lor","mar","vin","zar","xor","lis","zal"],
	"LYCAN": ["fang","wolf","lup","gar","fenrir","ald","thal","ra","grim","lok","rav","bar","lyk","var","rok","nath","thorn","dur","fen","skal","krag","fur","myr","vor","tyr","kaz","mor","tor","rak","nar","val","bal","zan","lor","or","lyc","gar","jor","kaz","luk","myr","rog","thal","ur","vor","wulf","xar","yor","zor","fang","wolf","lup","gar","fenrir","ald","thal","ra","grim","lok","rav","bar","lyk","var","rok","nath","thorn","dur","fen","skal","krag","fur","myr","vor","tyr","kaz","mor","tor","rak","nar","val","bal","zan","lor","or","lyc","gar","jor","kaz","luk","myr","rog","thal","ur","vor","wulf","xar","yor","zor"],
	"CYCLOPS": ["nok","gar","ruk","tok","gorn","kar","thak","mok","zor","rak","dar","gor","lag","zuk","nar","vok","rok","zar","gash","mur","tak","lur","goth","tok","kur","dush","nok","kar","dok","bar","gor","zak","krag","lur","vok","dar","rok","gar","lur","gor","tok","kar","zar","gash","gorn","nar","gor","lag","zuk","rok","zar","thok","gash","mur","tak","lur","goth","tok","kur","dush","nok","kar","dok","bar","gor","zak","krag","lur","vok","dar","rok","gar","lur","gor","tok","kar","zar","gash","gorn","nar","gor","lag","zuk","rok","zar","thok","gash","mur","tak","lur","goth","tok","kur","dush","nok","kar","dok","bar","gor","zak","krag","lur","vok","dar","rok","gar","lur","gor","tok","kar","zar","gash","gorn","nar","gor","lag","zuk","rok","zar","thok","gash","mur","tak","lur","goth","tok","kur","dush","nok","kar","dok"],
	"GIANT": ["gar","thak","mak","gash","ruk","tok","gor","lag","zuk","rok","kar","dush","mok","gor","nar","rog","drok","zul","tak","bur","guk","dok","mog","kur","dar","vok","lur","zar","goth","nok","tok","bar","dor","zak","krag","luk","nar","gash","vor","dak","rok","grok","zug","mur","ruk","dreg","mak","kar","zor","thok","gar","ruk","bar","zor","dag","mog","kar","dok","vok","mok","gur","zar","lok","mur","drok","gor","kar","goth","tok","vor","luk","zak","zar","ruk","tor","nar","grog","dak","mog","nok","bar","luk","dak","rok","dar","vor","mak","kor","nar","zar","gur","dok","lak","mar","tok","kar","nar","gor","mak","tok","rok","kar","zuk","nar","vor","mok","dok","gash","vor","kar","nar","rok","mak","kor","luk","gur","mok","kar","dok","nar","vor","zak","bar","nar","kor","tok","dak","vor","rok","gash","gur","mak"],
	"OGRE": ["nok","gar","ruk","tok","gorn","kar","thak","mok","zor","rak","dar","gor","lag","zuk","nar","vok","rok","zar","gash","mur","tak","lur","goth","tok","kur","dush","nok","kar","dok","bar","gor","zak","krag","luk","nar","gash","vor","dak","rok","grok","zug","mur","ruk","dreg","mak","kar","zor","thok","gar","ruk","bar","zor","dag","mog","kar","dok","vok","mok","gur","zar","lok","mur","drok","gor","kar","goth","tok","vor","luk","zak","zar","ruk","tor","nar","grog","dak","mog","nok","bar","luk","dak","rok","dar","vor","mak","kor","nar","zar","gur","dok","lak","mar","tok","kar","nar","gor","mak","tok","rok","kar","zuk","nar","vor","mok","dok","gash","vor","kar","nar","rok","mak","kor","luk","gur","mok","kar","dok","nar","vor","zak","bar","nar","kor","tok","dak","vor","rok","gash","gur","mak"],
	"HARPY": ["thra","ra","dra","thia","na","nia","ria","la","dra","za","sa","rina","lira","sha","tera","nys","via","tria","tha","sara","vira","nara","sira","kira","tra","dra","nara","lia","nia","ra","sha","via","tia","sera","dra","tra","ria","lira","sha","vira","tha","nara","sera","thra","ria","dra","lia","nira","sa","ria","lia","tra","nira","ra","dra","tha","nia","ria","la","dra","za","sa","rina","lira","sha","tera","nys","via","tria","tha","sara","vira","nara","sira","kira","tra","dra","nara","lia","nia","ra","sha","via","tia","sera","dra","tra","ria","lira","sha","vira","tha","nara","sera","thra","ria","dra","lia","nira","sa","ria","lia","tra","nira"],
	"MINOTAUR": ["ion","thos","rak","gore","tor","kar","gos","nor","ron","xar","gor","thar","drak","zor","mar","ran","gor","zor","mar","tar","thos","kar","zor","ran","rak","gore","tor","kar","gos","nor","ron","xar","gor","thar","drak","zor","mar","ran","gor","zor","mar","tar","thos","kar","zor","ran","rak","gore","tor","kar","gos","nor","ron","xar","gor","thar","drak","zor","mar","ran","gor","zor","mar","tar","thos","kar","zor","ran","rak","gore","tor","kar","gos","nor","ron","xar","gor","thar","drak","zor","mar","ran","gor","zor","mar","tar","thos","kar","zor","ran","rak","gore","tor","kar","gos","nor","ron","xar","gor","thar","drak","zor","mar","ran","gor","zor","mar","tar","thos","kar","zor","ran"],
	"KOBOLD": ["ik","ak","ix","ok","uk","ek","ax","ox","ex","ix","ix","ak","ik","ix","ok","uk","ek","ax","ox","ex","ix","ix","ak","ik","ix","ok","uk","ek","ax","ox","ex","ix","ix","ak","ik","ix","ok","uk","ek","ax","ox","ex","ix","ix","ak","ik","ix","ok","uk","ek","ax","ox","ex","ix","ix","ak","ik","ix","ok","uk","ek","ax","ox","ex","ix","ix","ak","ik","ix","ok","uk","ek","ax","ox","ex","ix","ix","ak","ik","ix","ok","uk","ek","ax","ox","ex","ix","ix","ak","ik","ix","ok","uk","ek","ax","ox","ex","ix","ix","ak","ik","ix","ok","uk","ek","ax","ox","ex","ix","ix","ak","ik","ix","ok","uk","ek","ax","ox","ex","ix","ix","ak","ik","ix","ok","uk","ek","ax","ox","ex","ix","ix"],
	"BEAST": ["fang","claw","roar","growl","snarl","hiss","bite","pounce","strike","slash","talon","venom","prowl","howl","grim","snap","fierce","savage","wild","brutal","feroc","rage","fury","tempest","thunder","storm","blaze","ash","flame","inferno","razor","scorch","blitz","dash","flash","streak","blaze","flare","bolt","jolt","sear","burn","crush","smash","crash","bash","rampage","wrath","vex","havoc","chaos","wrath","dread","dire","scorn","blight","plague","hex","cursed","doom","shade","shadow","phantom","specter","wraith","ghoul","ghost","spirit","haunt","poltergeist","revenant","banshee","lurker","watcher","seeker","fang","claw","roar","growl","snarl","hiss","bite","pounce","strike","slash","talon","venom","prowl","howl","grim","snap","fierce","savage","wild","brutal","feroc","rage","fury","tempest","thunder","storm","blaze","ash","flame","inferno","razor","scorch","blitz","dash","flash","streak","blaze","flare","bolt","jolt","sear","burn","crush","smash","crash","bash","rampage","wrath","vex","havoc","chaos","wrath","dread","dire","scorn","blight","plague","hex","cursed","doom","shade","shadow","phantom","specter","wraith","ghoul","ghost","spirit","haunt","poltergeist","revenant","banshee","lurker","watcher","seeker"],
	"CHIMERA": ["os","ax","or","is","us","or","ax","is","as","os","or","ax","us","or","ax","is","or","as","ax","or","us","or","ax","is","as","or","ax","is","us","or","ax","is","as","os","or","ax","us","or","ax","is","or","as","ax","or","us","or","ax","is","as","or","ax","is","us","or","ax","is","as","os","or","ax","us","or","ax","is","or","as","ax","or","us","or","ax","is","as","or","ax","is","us","or","ax","is","as","os","or","ax","us","or","ax","is","or","as","ax","or","us","or","ax","is","as","or","ax","is","us","or","ax","is","as","os","or","ax","us","or","ax","is","or","as","ax","or","us","or","ax","is","as","or","ax","is","us","or","ax","is","as","os","or","ax","us","or","ax","is","or","as","ax","or","us","or","ax","is","as"],
	"DRAGON": ["thar","drak","gorn","vyr","zor","nax","thos","gore","xar","voth","rax","mor","dral","xis","veris","theris","vyrn","raxis","dor","kron","fyr","gath","moros","kar","zorath","dran","zahar","dar","karr","vorn","raxis","ron","tar","vyn","gorn","thax","gath","dros","rion","zarn","thor","rax","gorn","dar","nar","zen"]
}

# RandomNumberGenerator instance for generating random values
var rng: RandomNumberGenerator = RandomNumberGenerator.new()

# Function to generate a random name based on faction
func generate_name(faction: String = "") -> String:
	faction = faction.to_upper()
	rng.randomize()
	var prefix = ""
	var suffix = ""
	
	if faction in name_prefixes:
		var prefixes = name_prefixes[faction]
		var suffixes = name_suffixes[faction]
		
		if prefixes.size() > 0:
			prefix = prefixes[rng.randi_range(0, prefixes.size() - 1)]
		if suffixes.size() > 0:
			suffix = suffixes[rng.randi_range(0, suffixes.size() - 1)]
	
	return prefix + suffix
